### ISSUE TITLE
Feature: Add favourites to calendar

### ISSUE THREAD

**Issue by sedrubal** [EventFahrplan/EventFahrplan#30]
At least for angels it was nice if there was an iCal export for the system calendar. Then you could add your shifts and favourite talks to the calendar an immediately see collisions. If you could subscribe to your favourites (in order to get updates) this was even better.

**Comment by johnjohndoe** [comment]
You can add individual favorites from the app to your calendar right now. There is no mass export such as ical yet.

Please explain what you mean by subscribing to your favorites.

**Comment by sedrubal** [comment]
I mean that the app works as stand alone calendar provider adding a new calendar source to the calendar app. Thus if you mark a new talk as favourite it will automatically appear in the calendar app...

**Comment by johnjohndoe** [comment]
Thank you for the explanation. Since others also asked for an integration with the _Engelsystem_ I talked to _Heaven_ about technical options.
Right now I can see the option to load personal angel shifts into the app as a separate column. I do not see the app acting as a stand alone calendar provider in the near future. I keep your feature request open as reminder until someone works on the integration.

**Comment by kordianbruck** [comment]
It would be really great to have a mass export for all favorites to be exported to ones own calendar. This would at least let a user see their favorite talks in their calendar app and engelsystem also allows to import shifts via iCal. 

A mass export should be pretty easy no? Would love to see that :heart:

**Comment by johnjohndoe** [comment]
@sedrubal Please notice that I worked on an integration of the Engelsystem shifts. The current implementation preview is open for [public testing](https://twitter.com/tbsprs/status/1205221641866883075). See  https://github.com/EventFahrplan/EventFahrplan/pull/200.

**Comment by joergi** [comment]
I tested it in the newest version. I guess this ticket can be closed @johnjohndoe

**Comment by johnjohndoe** [comment]
@sedrubal The Engelsystem shifts feature has been released since [version 1.41.0](https://github.com/EventFahrplan/EventFahrplan/milestone/20?closed=1) at [36C3.](https://events.ccc.de/congress/2019/) It was available at later events whenever some instance of the Engelsystem was used. 
Please comment here or close the issue if the feature satisfies your initial request.

**Comment by sedrubal** [comment]
Thank you! I'll close this and test it on the next event. If there are further issues, I'll reopen that issue.
