### ISSUE TITLE
F-Droid app not up to date

### ISSUE THREAD

**Issue by tagru** [EventFahrplan/EventFahrplan#39]
Is it possible to get the F-Droid app in sync with the playstore app on android so it shows the small rooms as well?

**Comment by johnjohndoe** [comment]
F-Droid is facing technical problems since before the start of the 34C3. That results in long waiting for the release of new versions. I have no influence on their process and can therefore not help on that side.

What you can do to get the full schedule is to load the full schedule manually:

1. Go to settings
2. Enter this URL as an alternative schedule URL:
> https://raw.githubusercontent.com/voc/34C3_schedule/master/everything.schedule.xml
3. Refresh the schedule via the menu icon on the main screen
4. Kill the app once by swiping it off the screen

Please close this issue if this is satisfying to you. Otherwise contact me via DECT 7879.

**Comment by tagru** [comment]
Works, thank you!

**Comment by rugk** [comment]
Awesome! Works?

**Comment by alexanderadam** [comment]
Oh no! I thought that both versions would be the same.
Will it happen again next year? Or is an application update for such cases not necessary any more?

**Comment by johnjohndoe** [comment]
@alexanderadam I had the same expectations. However, F-Droid could not resolve its build pipeline problems during the congress. See [activity log](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&limit=500&hidebots=0&days=14).
Next year we have to think about alternative, reliable distribution channels.

**Comment by rugk** [comment]
APK to GitHub releases, if you really need it. But it's all fine now, is not it? As long as you don't break compatibility a slightly older version of the app can still work and now we have the feature to include self-organized sessions.
