### ISSUE TITLE
Add link to the livestream

### ISSUE THREAD

**Issue by Rufus125** [EventFahrplan/EventFahrplan#549]
# Acknowledgments
Please check the following boxes with an `x` if they apply:
* [x] I have checked a few other issues labeled `Feature request` to see how they are written.
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that _EventFahrplan_ is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.

# Description

It would be nice to include the possibility to directly switch from the app to the livestream of media.ccc.de

Possible way to implement: 

* A configuration switch to show Button to open browser with livestream URL and a string configuration setting for the Livestream URL:

Default URL: https://streaming.media.ccc.de/
Customized URL: https://streaming.media.ccc.de/<eventcode> e.g. https://streaming.media.ccc.de/glt23

The button could either be shown at each room, if it is possible to link the room with the specific livestream page or at talks, where <no> is between the start and end time.

**Comment by johnjohndoe** [comment]
@Rufus125, thank you for your request.

This topic is loosely related to issues #48 and #52 which deal with the topic of session recordings.

Regarding **live content** I did some experiments in the past with streaming.media.ccc.de. I never integrated a feature in the app, though. You can find the **standalone library** and a **demo app** here:

- https://github.com/johnjohndoe/Brockman
- https://github.com/johnjohndoe/BrockmanDemo

I think it would still need some thoughts **if and how** and integration of live streams or links makes sense. The referenced projects would be a good starting point for investigations for anyone who is interested.

---

_To be transparent about my schedule: I will not have time to work on this in the near future (not in 2023) due to personal obligations._

**Comment by johnjohndoe** [comment]
I outlined above I won't have time to work on the feature request. Hence, I will close it here. It can be reopened at any time once someone has time to implement this. Thank you.
