### ISSUE TITLE
Change date parsing

### ISSUE THREAD

**Issue by saerdnaer** [EventFahrplan/EventFahrplan#92]
please use date time parsing library (e.g. SimpleDateFormat, c.f. https://stackoverflow.com/questions/13515168/android-time-in-iso-8601)  instead of manually splitting the date, thanks!

https://github.com/EventFahrplan/EventFahrplan/blob/545c22eadc54951d75c0bd00641c7e3660a3dcde/app/src/main/java/nerd/tuxmobil/fahrplan/congress/models/Lecture.java#L117-L128

**Comment by ideadapt** [comment]
I am on this. I try to fix #70 as well within the same PR.

**Comment by johnjohndoe** [comment]
> I am on this. I try to fix #70 as well within the same PR.

Please note that I already started using the library in a few places. I also believe it is a wise idea to wrap all date related code behind an interface as I started with in the [interface-time-class](https://github.com/EventFahrplan/EventFahrplan/tree/interface-time-class) branch (work in progress). All date/time operations must be unit tested.

**Comment by ideadapt** [comment]
@johnjohndoe I started working on this on branch [bugfix-92/spread-date-lib-usage](https://github.com/ideadapt/EventFahrplan/tree/bugfix-92/spread-date-lib-usage) (branched off from interface-time-class). After the 10th of January I would have time to discuss my work. Just to align our ideas and goals so that my work is not useless at the end :). Maybe we could have a call then? You can contact me via kunzätideadaptdotnet

**Comment by johnjohndoe** [comment]
@ideadapt I contacted you via email to we can arrange some call. Please note that the [interface-time-class](https://github.com/EventFahrplan/EventFahrplan/tree/interface-time-class) branch is not well tested - there work-in-progress. Keep this in mind if you base your work on top of it. Also feel free to "steal" the code in the commit and rewrite it to your needs.

**Comment by johnjohndoe** [comment]
@ideadapt Please note that - besides rebasing the branch - I also moved the `Clock` and `SystemClock` to its own package in the `commons` module to keep things tidy.
